### ISSUE TITLE
Not possible to start transfer from SOL if ZIG spending permission is not approved on destination network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#101]
1. Bug title: Not possible to start transfer from SOL if ZIG spending permission is not approved on destination network
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
  Chrome Version 97.0.4692.99 (Official Build) (x86_64)
5. Steps to reproduce:
   - Requirements
       - Rinkeby network is not approved 
   - Switch fromChain network to SOL
   - Switch toChain network to Rinkeby 
   - Try to start transfer from SOL to Rinkeby 
6. Actual result: Not possible to start transfer if destination network is not approved
7. Expected result: Possible to start transfer 

https://user-images.githubusercontent.com/88747529/150974254-8c9b7034-d87d-47ee-bd10-f16c53390410.mov

**Comment by german-schneck** [comment]
Validate now.

**Comment by QAPanda** [comment]
:white_check_mark:
