### ISSUE TITLE
Inactive Convert button after network switch

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#102]
1. Bug title: Inactive Convert button after network switch
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
  Chrome Version 97.0.4692.99 (Official Build) (x86_64)
5. Steps to reproduce:
   - Insert amount
   - Switch network
6. Actual result: Inactive Convert button
7. Expected result: Active Convert button or reset amount

https://user-images.githubusercontent.com/88747529/151440302-7f52ba2a-bafd-409f-8726-6b331ff448bb.mov

Same with MAX:
- Click max
- Switch to network with less balance => it will adjust amount
- Switch network again

Inactive Convert button on second switch

https://user-images.githubusercontent.com/88747529/151440465-627a216c-2c01-4c59-9227-07fb47e13f44.mov

**Comment by german-schneck** [comment]
When changing the network, the input value is reset. (the complete form). 

More efficient and secure solution.

**Comment by QAPanda** [comment]
:white_check_mark:
