### ISSUE TITLE
Color spec mismatch - dark mode 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#108]
1. Header
Spec:
- border #413ba0 -> rgb(65, 59, 160)
- address #989984 -> rgb(152, 153, 132)
- network name #829fff -> rgb(130, 159, 255)
- bg #171e35 -> rgb(23, 30, 53)
- dots #65647e -> rgb(101, 100, 126)
- Solana #3fc0bc -> rgb(63, 192, 188)
- zero balance #D16F6F -> rgb(209, 111, 111) (left alignment)
- border #121c42

![image](https://user-images.githubusercontent.com/88747529/151972545-aafcb640-51ef-4dd1-92d5-31134a7353c4.png)

2. MPT title
Spec:
![image](https://user-images.githubusercontent.com/88747529/151973942-2bf3e634-d5f7-43df-b682-9c34d4b24006.png)

3. ETH spec
![image](https://user-images.githubusercontent.com/88747529/151984507-58c2404b-c24d-4579-93eb-3fe71f4c5c97.png)

4. BSC spec
![image](https://user-images.githubusercontent.com/88747529/151985570-6623c8d1-67ab-42ba-892f-d42b1483effe.png)

5. POLY spec
![image](https://user-images.githubusercontent.com/88747529/151986186-a5ebb6e0-51bf-4875-a3a1-f4508364b9c7.png)

6. SOL spec
![image](https://user-images.githubusercontent.com/88747529/151987079-0aa2d2cf-5170-4e21-86f3-0d079fb2fa9f.png)

7. MPT spec
![image](https://user-images.githubusercontent.com/88747529/151979358-650159dd-b1fa-4876-b054-74c4f67ebf6a.png)

![image](https://user-images.githubusercontent.com/88747529/151979856-75cedfa6-a3bb-42c9-9525-e8b9c26ca7c6.png)

8. Approve button
![image](https://user-images.githubusercontent.com/88747529/152020505-5ed43991-1352-4898-8e34-2cb4849f7469.png)

9. Steps
![image](https://user-images.githubusercontent.com/88747529/152021451-28833d9b-b4df-4277-b84a-bc916dab3a29.png)

10. Footer 
![image](https://user-images.githubusercontent.com/88747529/152022254-46a65975-71bc-4323-a1d3-80b9bee8e12a.png)

11. Mode button
![image](https://user-images.githubusercontent.com/88747529/152023604-2d661896-0249-4d43-8b48-d530550d67df.png)

**Comment by QAPanda** [comment]
Full dark mode color spec:
<img width="1128" alt="bridge-dark-spec" src="https://user-images.githubusercontent.com/88747529/152021614-d896b8c4-0e37-46d5-affa-16e26b66683c.png">

**Comment by QAPanda** [comment]
1 :white_check_mark:
Except balance - left alignment
<img width="330" alt="image" src="https://user-images.githubusercontent.com/88747529/153503295-24b1c9f0-70be-4591-a92a-5a42b7722a43.png">
<img width="447" alt="image" src="https://user-images.githubusercontent.com/88747529/153670181-a4207562-9a1f-4b03-b62c-a883862e4f23.png">

Design:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/88747529/153503892-d77f33f6-2636-413f-a0c4-596aba7fa5b7.png">

**Comment by QAPanda** [comment]
2 :white_check_mark:
3 :white_check_mark:

**Comment by QAPanda** [comment]
4 :white_check_mark:
5 :white_check_mark:
6 :white_check_mark:

**Comment by QAPanda** [comment]
7. A few things left:
<img width="490" alt="image" src="https://user-images.githubusercontent.com/88747529/153672107-76ba50be-f3af-428a-83ea-0175bc5ad21e.png">

**Comment by QAPanda** [comment]
8. A few things left: 
<img width="418" alt="image" src="https://user-images.githubusercontent.com/88747529/153672849-462a5899-1610-40aa-9203-96fbf0012bcf.png">

**Comment by QAPanda** [comment]
9. Left:
<img width="594" alt="image" src="https://user-images.githubusercontent.com/88747529/153673401-45fe896e-29ae-4cb8-8d52-ed1531c3e540.png">

**Comment by QAPanda** [comment]
10 :white_check_mark:

**Comment by QAPanda** [comment]
11. Fill is missing:
<img width="708" alt="image" src="https://user-images.githubusercontent.com/88747529/153673656-c1d700ab-ddf2-4847-b674-b9a82c1f953f.png">

**Comment by german-schneck** [comment]
1. Done

**Comment by german-schneck** [comment]
7. done

**Comment by german-schneck** [comment]
8. Done

**Comment by german-schneck** [comment]
11. @QAPanda we need the originals icons in SVG format. I use react ionicons.

**Comment by german-schneck** [comment]
9 Done. If it is still wrong, could you clarify which parts should have a certain color?

**Comment by QAPanda** [comment]
1 :white_check_mark:
Except balance - left alignment
<img width="330" alt="image" src="https://user-images.githubusercontent.com/88747529/153503295-24b1c9f0-70be-4591-a92a-5a42b7722a43.png">
Design:
<img width="344" alt="image" src="https://user-images.githubusercontent.com/88747529/153503892-d77f33f6-2636-413f-a0c4-596aba7fa5b7.png">
7 :white_check_mark:
8 :white_check_mark:
9 :white_check_mark:
11. SVG files sent to Slack

**Comment by QAPanda** [comment]
1 and 11 moved here https://github.com/zignaly-open/zignaly-open-bridge/issues/111
