### ISSUE TITLE
Not possible to transfer float amount form SOL to other networks

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#112]
1. Bug title: Not possible to transfer float amount form SOL to other networks
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.3 /
  Chrome Version 98.0.4758.102 (Official Build) (x86_64)
5. Steps to reproduce:
   - Switch fromChan network to SOL
   - Switch toChain network to Rinkeby (same for BSC and POLY)
   - Insert float type amount - more than one decimal (e.g 8.6533)
   - Confirm transfer in Phantom wallet
6. Actual result: Transaction is looping and is never processed 
7. Expected result: Successful transfer 

https://user-images.githubusercontent.com/88747529/154798704-2965e34b-bd18-4847-b443-6cbcc8c5031e.mov

**Comment by QAPanda** [comment]
Note: Specifically related to 2+ decimals

<img width="943" alt="image" src="https://user-images.githubusercontent.com/88747529/154798869-fa6326ba-cebe-4b2f-8501-84ac648e747a.png">

**Comment by german-schneck** [comment]
You have a ss from the bridge server console?

**Comment by QAPanda** [comment]
:white_check_mark:
