### ISSUE TITLE
TypeError: Failed to fetch 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#114]
1. Bug title: Type error on WalletConnect 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - In Chrome open: https://bridgetest.zignaly.com/
   - Click Connect MM Wallet button
   - Click WalletConnect button in modal
7. Actual result: TypeError: Failed to fetch 
8. Expected result: Open without console error

https://user-images.githubusercontent.com/88747529/159138452-54014248-2cb4-4f5d-84d2-5a0e40120311.mov

**Comment by german-schneck** [comment]
I can reproduce it without errors:
![image](https://user-images.githubusercontent.com/15254932/159170107-283b1c16-27a1-475d-83fc-9394f78846eb.png)


Maybe the problem is realted to the wallet connect provider server.
