### ISSUE TITLE
 Loop if switch network in UI before connecting wallet  

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#115]
1. Bug title: Loop if switch network in UI before connecting wallet  
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - In Chrome open: https://bridgetest.zignaly.com/
   - In bridge UI switch network (e.g. to BSC)
   - Unlock MM wallet
   - Confirm switch in MM wallet
6. Actual result: Loop on network switch 
7. Expected result: Switch network

https://user-images.githubusercontent.com/88747529/159138643-579f47dd-7366-493c-8eae-3c93fc6ff1bf.mov

Note: Related to mainnet.

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
