### ISSUE TITLE
Loop on Convert button

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#116]
1. Bug title: Loop on Convert button
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - In Chrome open: https://bridgetest.zignaly.com/
   - Click Connect MM Wallet button
   - Click MM in modal
   - Unlock MM wallet
   - Click OK in gif modal
   - Reopen MM and confirm account connection
6. Actual result: Convert button is looping after connection 
7. Expected result: Available Approve/Convert button

https://user-images.githubusercontent.com/88747529/159138887-09158cf0-c254-42eb-86e1-3efbc223f7a6.mov

Same if you skip last two steps:

https://user-images.githubusercontent.com/88747529/159138956-523f265b-d4fb-4059-a7b2-30ca471c234a.mov

Note: Related to mainnet.

**Comment by german-schneck** [comment]
Try it now.

**Comment by QAPanda** [comment]
:white_check_mark:
