### ISSUE TITLE
Blank screen and type error on network switch in MM

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#117]
1. Bug title: Blank screen and type error 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - In Chrome open: https://bridgetest.zignaly.com/
   - Open MM wallet (note that wallet is not connected to the bridge yet)
   - Switch network in MM wallet 
6. Actual result: Blank screen and type error 
7. Expected result: Switch wallet in MM 

https://user-images.githubusercontent.com/88747529/159139238-6b1bd646-3b7e-418e-b204-108e3043e17e.mov

It is the same on testnet:
- Open MM wallet and disconnect bridge
- Switch network from Rinkeby to BSC Testnet in MM wallet
 
https://user-images.githubusercontent.com/88747529/159139350-5c63b06c-ccda-4505-88f6-0174a59368c6.mov

**Comment by german-schneck** [comment]
Try it now

**Comment by QAPanda** [comment]
:white_check_mark:
