### ISSUE TITLE
Network switch

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#118]
1. Bug title: Network switch 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - fromChain network is Poly and toChain network is BSC Testnet
   - Switch fromChai network to BSC Testnet
   - Confirm switch in MM wallet
6. Actual result: toChain network switch to Rinkeby 
7. Expected result: toChain network Poly
Note: Same in opposite direction.

https://user-images.githubusercontent.com/88747529/159139550-a7314e0d-c60f-4a5a-a0cf-ebe1c759b7dc.mov

Same with this steps:
   - fromChain network is Poly and toChain network is Rinkeby 
   - Switch fromChai network to Rinkeby
   - Confirm switch in MM wallet
Actual: toChain switches to BSC instead to Poly

https://user-images.githubusercontent.com/88747529/159139645-ae8ceb9c-bcd4-469c-8804-e6e718531ce7.mov

**Comment by german-schneck** [comment]
Try it now

**Comment by QAPanda** [comment]
:white_check_mark:
