### ISSUE TITLE
Not possible to switch network using Click to switch link 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#120]
1. Bug title: Not possible to switch network using Click to switch link 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - Start transfer
   - Confirm transfer in MM wallet
   - Wait for transfer confirmation (wait until Switch Network button appears) 
   - Click on status tooltip and click Click to switch link 
6. Actual result: Uncaught TypeError; not possible to switch network 
7. Expected result: Networks switches 

https://user-images.githubusercontent.com/88747529/159140001-85b38111-edaa-4aba-a59f-48f2f1217ec5.mov

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
