### ISSUE TITLE
Error: Invalid contract address or ENS name 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#121]
1. Bug title: Error: Invalid contract address or ENS name 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 99.0.4844.74 (Official Build) (x86_64)
5. Steps to reproduce:
   - Start transfer from SOL to Rinkeby
   - Confirm transfer in Phantom wallet
   - Wait for transfer to be processed
   - Click on Switch Network button 
6. Actual result: Error: Invalid contract address or ENS name 
7. Expected result: Switch without errors 
Note: Rinkeby was already selected network in MM wallet.

https://user-images.githubusercontent.com/88747529/159140186-fcc56f8f-785f-49b2-ab1f-ebc16d131d63.mov

**Comment by german-schneck** [comment]
Done, try it!

**Comment by QAPanda** [comment]
:white_check_mark:
