### ISSUE TITLE
Same network on both sides after MM reconnection 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#123]
1. Bug title: Same network on both sides after MM reconnection 
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 / All browsers
5. Steps to reproduce:
   - Switch fromChain to SOL
   - toChain is Poly (same network selected in MM wallet)
   - Disconnect MM wallet from bridge using Disconnect button 
   - Reconnect MM  wallet
6. Actual result: Poly on both sides
7. Expected result: SOL on fromChain side and Poly on toChain side

https://user-images.githubusercontent.com/88747529/159894308-00a86dbb-7a1b-4657-b683-f18c26a429b1.mov

Note: Probably same issue related to MM reconnection.
Steps:
- fromChain network is SOL
- toChain network is BSC
- in MM selected network is Rinkeby
- Disconnect bridge from MM using Disconnect button
- Reconnect MM wallet
Actual: Rinkeby on fromChain side and BSC on toChain side
Expected: SOL on fromChain side and BSC on toChain side (Rinkeby in header as it is selected network in MM)

https://user-images.githubusercontent.com/88747529/159895126-d31a02df-31b5-41f2-bd73-76be191b8cfb.mov

**Comment by german-schneck** [comment]
Check this issue now

**Comment by QAPanda** [comment]
:white_check_mark:
