### ISSUE TITLE
Delay in balance update

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#124]
1. Bug title: Delay in balance update
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 / All browsers
5. Steps to reproduce:
   - Switch between networks 
   - Look at balances (both sides and header) 
6. Actual result: Delay in balance update
7. Expected result: Balances update on switch 

https://user-images.githubusercontent.com/88747529/159895871-542db139-d0c4-4f5b-9463-69e3e4f67e3a.mov

**Comment by QAPanda** [comment]
Reconnection:

https://user-images.githubusercontent.com/88747529/159907986-539686b3-e904-4f4b-9e4e-7f7317399569.mov

**Comment by german-schneck** [comment]
Check the reconnection

**Comment by QAPanda** [comment]
Still happening: 

https://user-images.githubusercontent.com/88747529/160016478-0fff2fe8-7d95-4bbb-b7aa-62a12fbbd414.mov

**Comment by appsmonkey** [comment]
Open it with proxy like Charles https://www.charlesproxy.com or similar and watch for network call. Is network request delayed, response delayed or logic of updating. that will tell you how to fix it.

**Comment by QAPanda** [comment]
Steps from the above are fixed.

Balance update delays only under these steps:
- Switch fromChain to SOL
- toChain is BSC but not related to the network
- Disconnect MM wallet 
- Switch toChain network to Rinkeby/Poly
- Reconnect MM wallet
BSC balance update in the header is delaying 

https://user-images.githubusercontent.com/88747529/160231811-dcd7805f-c495-4470-b3b0-f96b225b6aa6.mov

**Comment by QAPanda** [comment]
:white_check_mark:
