### ISSUE TITLE
Balance is not updating in header if network is not selected as toChain network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#125]
1. Bug title: Balance is not updating in header if network is not selected as toChain network
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.3 / All browsers
5. Steps to reproduce:
   - Switch fromChain network to SOL
   - Switch toChain network to Poly
   - Send transfer from SOL to Poly
   - Confirm transfer in Phantom wallet
   - Switch to Poly and claim transaction
   - Switch fromChain network back to SOL
   - Switch toChain network to BSC
6. Actual result: Poly balance is not updating in header
7. Expected result: Poly balance updates in header 

https://user-images.githubusercontent.com/88747529/159900490-643bce7d-9e9d-45c1-985f-f01c5ed4d239.mov

**Comment by german-schneck** [comment]
Check this issue now

**Comment by QAPanda** [comment]
:white_check_mark:
