### ISSUE TITLE
Approve loop

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#126]
1. Bug title: Approve loop
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 / All browsers
5. Steps to reproduce:
   - Switch network to Rinkeby (not related to network)
   - Click Approve button
   - Confirm permission in MM wallet
   - Switch network to BSC or Poly
6. Actual result: Approve button is lopping on BSC/Poly
7. Expected result: Available Approve button on BSC/Poly network

https://user-images.githubusercontent.com/88747529/160122120-0b25d3c0-d3ec-4c42-be4d-665f931a9f47.mov

**Comment by german-schneck** [comment]
Solved, you can try it now.

**Comment by QAPanda** [comment]
:white_check_mark:
