### ISSUE TITLE
Bridge is not updating solana state when switch from mainnte to devnet or testnet 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#128]
1. Bug title: Bridge is not updating solana state when switch from mainnte to devnet or testnet 
2. URL: https://bridge.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
  Chrome Version 100.0.4896.60 (Official Build) (x86_64)
5. Steps to reproduce:
   - Check Sol state in bridge UI
   - In Phantom wallet change network from mainnet to devnet (or testnet)
   - Check Sol state in bridge UI
6. Actual result: Error: State is not updating (active mainnet state)
7. Expected result: Bridge UI updates Sol state on switching between networks 

https://user-images.githubusercontent.com/88747529/160796277-9ba46a5e-757f-4912-863a-c8121092d41a.mov

**Comment by QAPanda** [comment]
If you start transfer in this setup, confirmation will point to devnet/tesnet and the transaction will never be executed:
https://explorer.solana.com/tx/KGrARTNvaVg3gZ4YPYjs1rvsChswTjK2nM1A1Eak4kXjK2vsQJe1edgLdUebxRtfynqWCCzsxKnnyf9AYaAxsE7

Sol balance will remain unchanged but transaction will stuck in UI:
<img width="925" alt="image" src="https://user-images.githubusercontent.com/88747529/160797722-76d961f8-fb51-4575-a9b1-d0334dd79607.png">

**Comment by german-schneck** [comment]
I have made several fixes related to this, you can try it.
