### ISSUE TITLE
Not possible to connect MM wallet when loading bridge from cache 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#130]
1. Bug title: Not possible to connect MM wallet when loading bridge from cache 
2. URL: https://bridge.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.5 /
   Chrome Version 1.36.122 Chromium: 99.0.4844.88 (Official Build) (x86_64)
5. Steps to reproduce:
   - In Brave open https://bridge.zignaly.com/
   - Connect wallets 
   - Kill browser 
   - Reopen browser
   - Reopen https://bridge.zignaly.com/
   - Click Connect MM wallet button
   - Unlock wallet 
6. Actual result: Not possible to connect until reload page
7. Expected result: Smooth connection
 
https://user-images.githubusercontent.com/88747529/160828585-daefbff4-9527-4cff-bb49-784c4d5cdb6a.mov

**Comment by QAPanda** [comment]
If connecting this way (reloading page and connect), first disconnection in MM will also need reload:

https://user-images.githubusercontent.com/88747529/160829404-9ac6d7cf-1b31-4b06-9cdf-cf277ee27299.mov

**Comment by german-schneck** [comment]
I have sent the arrreglo.

Right now: When starting the app after closing the browser, if metamask is not initialized it will force the user to reload the page.
