### ISSUE TITLE
Possible UX Improvements - Blank screen when disconnecting MM from the bridge

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#15]
1. Bug title: Blank screen when disconnecting MM from the bridge
2. URL: https://bridgetest.zignaly.com/?testnet=true
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.5.2 / Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Open MM extension
   - Click on `Connected` button (top left)
   - Disconnect MM account from the bridge
<img width="1097" alt="Screen_Shot_2021-08-21_at_10_38_41_AM" src="https://user-images.githubusercontent.com/6954890/130316208-6e063a9e-3162-4711-947a-06b01456e3ce.png">
6. Actual result: Blank screen

<img width="1438" alt="Screen_Shot_2021-08-21_at_10_44_26_AM" src="https://user-images.githubusercontent.com/6954890/130316285-a14eb474-9c31-4657-a55e-1e4dfcef9e25.png">

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/6954890/130316023-49841eb1-42d2-4d82-a415-5ab4d23fffbe.png">
7. Expected result: E.g.

<img width="1097" alt="image" src="https://user-images.githubusercontent.com/6954890/130316066-fc749e3d-5598-48c2-8434-046a5138c072.png">

**Comment by QAPanda** [comment]
Same if you switch to unsupported network: 

<img width="1440" alt="Screen Shot 2021-08-21 at 1 07 39 PM" src="https://user-images.githubusercontent.com/88747529/130320027-46b1d663-d22a-4dc2-882c-4c1638db21cb.png">

**Comment by gebo96** [comment]
Ready to test.

**Comment by QAPanda** [comment]
Switch to unsupported network - verified :white_check_mark:

MM disconnection - not blank page, but it shows the same message as for unsupported network.
Probably it is way better to have `Connect with MM` screen here.

<img width="617" alt="Screen_Shot_2021-08-23_at_8_01_11_PM" src="https://user-images.githubusercontent.com/88747529/130494958-485d1124-903f-4ca2-b085-e90af3345ec4.png">

![disconnection](https://user-images.githubusercontent.com/88747529/130495999-6b418552-f1b7-465f-9acc-f92120a4bf5e.gif)
