### ISSUE TITLE
Balance is not updated after the transfer is processed 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#16]
1. Bug title: Balance is not updated after the transfer is processed 
2. URL: https://bridgetest.zignaly.com/?testnet=true
3. Public address/txHash: 0xFcb3E959c2360e106b3fAF3f4cDA5DD75081bA3f
4. OS/Browser version: macOS Big Sur version 11.5.2 / Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: https://bridgetest.zignaly.com/?testnet=true
   - Connect to MM wallet
   - Switch to BSC Testnet (or Rinekby Test Network) -> not related to network
   - Start transfer
   - Confirm transfer in MM wallet
   - Switch to Rinekby Test Network (or BSC Testnet) 
   - Claim tokens
   - Confirm transfer in MM wallet
   - See the balance in the left box
6. Actual result: Balance is not updated
<img width="1152" alt="Screen_Shot_2021-08-21_at_11_30_30_AM" src="https://user-images.githubusercontent.com/88747529/130317717-34c64a3f-29ba-4605-b801-1cab2840709c.png">
It is same on the top right:
<img width="561" alt="Screen_Shot_2021-08-21_at_11_30_44_AM" src="https://user-images.githubusercontent.com/88747529/130317734-48deebfa-c147-4de6-aab2-d583f879ad06.png">

7. Expected result: Balance is updated after the transfer is successfully processed
Note: If reload the page, balance updates.
<img width="1215" alt="Screen_Shot_2021-08-21_at_11_31_14_AM" src="https://user-images.githubusercontent.com/88747529/130317755-df41019a-677e-4030-a397-3c313cec765b.png">
Same here: 
<img width="561" alt="Screen_Shot_2021-08-21_at_11_30_50_AM" src="https://user-images.githubusercontent.com/88747529/130317765-6a29127b-3cce-48c4-88c6-c37646f8dd5f.png">

**Comment by gebo96** [comment]
Hello, this bug is fixed, it will be in the next deployment so you can validate.

**Comment by QAPanda** [comment]
Hi, thank you!

Has been validated :white_check_mark:
