### ISSUE TITLE
Claiming loop

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#20]
1. Bug title: Claiming loop
2. URL: https://bridgetest.zignaly.com/?testnet=true
3. Public address/txHash: 0xFcb3E959c2360e106b3fAF3f4cDA5DD75081bA3f 
4. OS/Browser version: macOS Big Sur version 11.5.2 / Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: https://bridgetest.zignaly.com/?testnet=true
   - Connect MM wallet
   - Switch to BSC Testnet
   - Start transfer
   - Confirm transfer in MM wallet
   - Switch to Rinkeby Test Network
   - Claim tokens
   - Confirm transfer in MM wallet
   - Double click on 'loading' (MM shows option to confirm transaction again)
   - Confirm transfer in MM wallet again (https://rinkeby.etherscan.io/tx/0xa1fc710e3b5533a1a74dab26ae2d2a6f82d4ac290e34a167af00050b221242b4)
![image](https://user-images.githubusercontent.com/88747529/130324210-5d19cf27-110d-49e3-bc4d-3d123853e069.png)
6. Actual result: Ends up in a loop
![image](https://user-images.githubusercontent.com/88747529/130324229-f1f8ec95-86b1-4316-95cf-59c67dc11b4f.png)

Note: Transfer started on August 20, 2021, and was successful. But loop is still there.
If double click on 'loading', console shows error:
<img width="1429" alt="Screen_Shot_2021-08-21_at_1_55_16_PM" src="https://user-images.githubusercontent.com/88747529/130324292-ea9e82f7-184c-4310-bf1d-ba36f0e044e6.png">

**Comment by jgomes79** [comment]
Ready to test

**Comment by QAPanda** [comment]
All good here. I just still have a pending transfer and it would be great if possible to clean it up somehow.

![image](https://user-images.githubusercontent.com/88747529/130512467-fcd6f5fb-63c9-4ff2-a2ab-704ba8b99ead.png)
