### ISSUE TITLE
Pending transfers box disappears 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#22]
1. Bug title: `Pending transfers` box disappears 
2. URL: https://bridgetest.zignaly.com/?testnet=true
3. Public address/txHash: 0x47850A15f96f74368F4Aea1D3cCb8C48BDF633EA
4. OS/Browser version: macOS Big Sur version 11.5.2 /
   Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open https://bridgetest.zignaly.com/?testnet=true
   - Connect your MM wallet
   - Disconnect MM account from the bridge
   - Refresh the page
   - Connect MM account (the same you disconnected)
   - Start transfer
   - Confirm transfer in MM wallet
   - Look at `Pending transfers` box 

![pending-transactions](https://user-images.githubusercontent.com/88747529/130370517-61d59970-d260-420d-b8a2-b2c105c6b628.gif)

6. Actual result: `Pending transfers` box disappears (have to refresh the page to shows up)
7. Expected result: `Pending transfers` box with a pending transaction

Note: It happens only on the first transfer, after disconnect/connect.

**Comment by gebo96** [comment]
Ready to test.

**Comment by QAPanda** [comment]
:white_check_mark: verified.
