### ISSUE TITLE
The `Pending transfers` box doesn't update after you switch the account

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#23]
1. Bug title: The `Pending transfers` box doesn't update after you switch the account
2. URL: https://bridge.zignaly.com/?testnet=true
3. Public address/txHash: 0xFcb3E959c2360e106b3fAF3f4cDA5DD75081bA3f and
   0x47850A15f96f74368F4Aea1D3cCb8C48BDF633EA
4. OS/Browser version: macOS Big Sur version 11.5.2 /
   Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: https://bridge.zignaly.com/?testnet=true
   - Connect MM wallet (connect acc. 1 and acc. 2)
   - Switch to `Account 1`
   - Look at the `Pending transfers` box and balances
   - Switch to `Account 2`
   - Look at the `Pending transfers` box and balances
  
![switch-acc-not-updating-pending-box](https://user-images.githubusercontent.com/88747529/130449511-21171f5a-44f6-4a11-97ff-bbc4dc6dc3c5.gif)

6. Actual result: `Pending transfers` box is not updated. Balances are updated.
   Note: Reload the page to update `Pending transfers`. 
7. Expected result: `Pending transfers` box matches Account 2

**Comment by jgomes79** [comment]
Ready to test

**Comment by QAPanda** [comment]
:white_check_mark: verified
