### ISSUE TITLE
Fail with error 'ERC20: transfer amount exceeds balance'

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#24]
1. Bug title: Try to transfer MAX amount several times in a row
2. URL: https://bridge.zignaly.com/?testnet=true
3. Public address/txHash: 0x47850A15f96f74368F4Aea1D3cCb8C48BDF633EA
First transaction: https://rinkeby.etherscan.io/tx/0xebe9b80fb516299e3bc3d0063320f52f58c7dd2c4f0d1de434dcbb7b184bcac0
https://testnet.bscscan.com/tx/0x31410d8b3ebd85144460ad6e6c02bb8255388f9544f49b6aa068aba7961222a0
Second one:
https://rinkeby.etherscan.io/tx/0x3e2c3da0875368629eced4078e3b66e29a1a4b3bcff2600bf6e5d0177331cbae
4. OS/Browser version: macOS Big Sur version 11.5.2 /
   Brave: Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: https://bridge.zignaly.com/?testnet=true
   - Connect MM wallet 
   - Switch to Rinkeby Test Network
   - Select `MAX` and press `CONVERT NOW`
   - Confirm transaction in MM wallet
   - In the very next second, select `MAX` again and press `CONVERT NOW`
   - Confirm transaction in MM wallet
6. Actual result: The first transaction goes through and gets claimed on the BSC, other fails (Fail with error 'ERC20: transfer amount exceeds balance') but continues to appear in `Pending transactions` box at the top

![pending-loop](https://user-images.githubusercontent.com/88747529/130456936-ca119cbd-d542-4716-bbcf-7e6ce99f39f8.gif)

<img width="709" alt="Screen_Shot_2021-08-23_at_3_40_24_PM" src="https://user-images.githubusercontent.com/88747529/130457784-c1726e07-853a-4db4-b943-5d53eb0814d0.png">

**Comment by jgomes79** [comment]
Ready to test.

**Comment by QAPanda** [comment]
Issue still present:

https://rinkeby.etherscan.io/tx/0x151c1fb6d03e2e30b34f572f50cdb0428a274b0c29c7767eaa36537644ffdabc

<img width="1261" alt="Screen_Shot_2021-08-23_at_9_42_17_PM" src="https://user-images.githubusercontent.com/88747529/130510110-ad76ce27-407c-4d18-8c8d-e30d97d4bfb0.png">

https://testnet.bscscan.com/tx/0xfa1d6c58a36181101d2830c0ea718718627678bdb93c091f0098cdcdb50c8317

<img width="1228" alt="Screen_Shot_2021-08-23_at_9_45_49_PM" src="https://user-images.githubusercontent.com/88747529/130510160-868a3fe1-7ccd-4a1c-b5d7-564f091ce2ad.png">

![max2x](https://user-images.githubusercontent.com/88747529/130510189-68d4dd4e-923b-409f-9e00-cbdfd916cc4a.gif)

**Comment by jgomes79** [comment]
Hi, try with the lastest version deployed. Seeing the video, I think you have test before the deployment, because now we deactivate the "confirm now" button until the transaction is confirmed.

**Comment by QAPanda** [comment]
:white_check_mark: verified
