### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#27]
1. Bug title: Error 404
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
6. Actual result:  Error 404

<img width="1427" alt="404" src="https://user-images.githubusercontent.com/88747529/134738767-1e77c2b7-e7d6-4c5d-9f33-d650df44828b.png">

**Comment by german-schneck** [comment]
Done.

**Comment by QAPanda** [comment]
Verified :white_check_mark:
