### ISSUE TITLE
Missing '? Help' redirection

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#28]
1. Bug title: Missing '? Help' redirection
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Click to '? Help' tooltip (top right)
6. Actual result:  Nothing happens 
7. Expected result: Redirects to: https://help.zignaly.com/hc/en-us/categories/4405994922898-ZIG-Coin 

Add env var:
REACT_APP_HELP=https://help.zignaly.com/hc/en-us/categories/4405994922898-ZIG-Coin

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
