### ISSUE TITLE
Change 'How it Works' redirection

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#29]
1. Bug title: Change 'How it Works' redirection and remove 'Tutorials'
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Click to 'How it Works' (bottom left)
6. Actual result: Redirects to: https://zignaly.com
7. Expected result: Redirects to: https://help.zignaly.com/hc/en-us/sections/4406103312914-ZIG-Token-Bridge-Ethereum-Binance-Smart-Chain

Change env var:
REACT_APP_HOW_IT_WORKS=https://help.zignaly.com/hc/en-us/sections/4406103312914-ZIG-Token-Bridge-Ethereum-Binance-Smart-Chain

Note:
Since both 'How it Works' and 'Tutorials' have the same redirection please remove 'Tutorials' button.
![image](https://user-images.githubusercontent.com/88747529/134740176-d2cd9327-4c9c-4582-8813-f300f2acf69c.png)

Remove env var:
REACT_APP_TUTORIALS=https://help.zignaly.com/hc/en-us/sections/4406103312914-ZIG-Token-Bridge-Ethereum-Binance-Smart-Chain

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
