### ISSUE TITLE
Switch network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#30]
1. Bug title: Switch network
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect bridge to MM wallet
   - Networks starting point:
      - Convert ZIG form Chain: Rinkeby Testnet (balance 299,110)
      - Convert to Chain: BSC Testnet (balance 890)
   - Switch network to Polygon Testnet (in 'Convert ZIG form Chain' select 'Matic Testnet'; balance 300,000)
   - Confirm switch network in MM wallet
6. Actual result: 'Convert to Chain:' automatically changes to Rinkeby, but with BSC Testnet balance (890)
<img width="579" alt="image-20210924163415920" src="https://user-images.githubusercontent.com/88747529/134742005-8160a678-e913-4387-a8ee-24b37ab8c09f.png">
7. Expected result: 'Convert to Chain:' Keeps BSC Testnet network selected

**Comment by QAPanda** [comment]
Not related to one network:
Gifs: https://www.dropbox.com/sh/k10c3kdqfi1xix8/AAC5dmh5NxJh2FHTAp_rvtRPa?dl=0

**Comment by QAPanda** [comment]
Same on transfer:
   - Start transfer >>> BSC Testnet to Polygon Testnet 
   - Confirm transfer in MM
   - Switch to Polygon Testnet  to claim

Actual: 'Convert to Chain' side changes network to Rinekby Testnet
Expected: 'Convert to Chain' side keeps BSC Testnet selected

![switch-low](https://user-images.githubusercontent.com/88747529/134765155-a3da1597-7128-47ab-8b8f-a40af61f4f4b.gif)

**Comment by QAPanda** [comment]
Errors on switch

Polygon:
Error: underlying network changed (event="changed", network={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)

Error: underlying network changed (event="changed", network={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)

Error: underlying network changed (event="changed", network={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)
index.jsx:337 {stateToProps: {…}, currentChainI

Error: underlying network changed (event="changed", network={"name":"rinkeby","chainId":4,"ensAddress":"0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e"}, detectedNetwork={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)

Error: underlying network changed (event="changed", network={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)

Error: underlying network changed (event="changed", network={"name":"maticmum","chainId":80001,"ensAddress":null,"_defaultProvider":null}, detectedNetwork={"name":"bnbt","chainId":97,"ensAddress":null,"_defaultProvider":null}, code=NETWORK_ERROR, version=providers/5.4.5)
    at e.value (index.ts:225)
    at r.<anonymous> (base-provider.ts:835)
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:294)
    at Generator.next (runtime.js:119)
    at o (2.c02c141f.chunk.js:2)

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:

**Comment by QAPanda** [comment]
Just switch works fine. 

But on transfer 'to Chain' side changes to Rinekby.

![switch-low](https://user-images.githubusercontent.com/88747529/134765155-a3da1597-7128-47ab-8b8f-a40af61f4f4b.gif)
