### ISSUE TITLE
Balance is not updated after claim

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#31]
1. Bug title: Balance is not updated after claim
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  0x47850A15f96f74368F4Aea1D3cCb8C48BDF633EA
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Start transfer from Rinkeby to BSC Testnet (110 ZIGs)
      - Starting point: Rinkeby balance 299110, BSC Testnet balance 890
   - Confirm transfer in MM wallet
   - Switch network to BSC Testnet
   - Claim transaction (click on 'Claim' button)
   - Confirm transaction in MM wallet
   - See BSC Testnet balance
6. Actual result: Balance is not updated (need to reload the page)
<img width="1440" alt="image-20210924191139657" src="https://user-images.githubusercontent.com/88747529/134744865-f968797f-d56e-495b-8696-d3e839df9254.png">
Second example:

<img width="1331" alt="image-20210924192432535" src="https://user-images.githubusercontent.com/88747529/134744882-ceeaf1be-bf5f-45e7-8146-c6d25515dea9.png">
7. Expected result: Balance updated

Note: Related to transfers Rinkeby to BSC, Rinkeby to Polygon, BSC to Polygon, Polygon to BSC.

**Comment by german-schneck** [comment]
Pending new revision.

**Comment by QAPanda** [comment]
Now end up in a loop: https://github.com/zignaly-open/zignaly-open-bridge/issues/41

**Comment by QAPanda** [comment]
Still active issue, need to reload page to update balance.
Related to BSC and Poly

![image](https://user-images.githubusercontent.com/88747529/136205188-85676e4e-9a09-4f3e-a057-38003380c160.png)

**Comment by german-schneck** [comment]
Ready for test.

**Comment by QAPanda** [comment]
:white_check_mark:
