### ISSUE TITLE
Not possible to click 'Click to switch' link

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#32]
1. Bug title: Not possible to click 'Click to switch' link
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Start transfer
   - Confirm transfer in MM
   - In 'My Pending Transactions' click on 'Ready to claim !' tooltip
   - Try to click  'Click to switch' link
6. Actual result: Tooltip shows on hover and is not possible to click 'Click to switch' 
<img width="1002" alt="image-20210924170654768" src="https://user-images.githubusercontent.com/88747529/134746120-07f66525-20e2-435c-8c42-656db08726be.png">

![click-to-switch](https://user-images.githubusercontent.com/88747529/134746128-88809c22-e249-4dbb-ac08-5ddd1baaa083.gif)
7. Expected result: Possible way to switch network

**Comment by german-schneck** [comment]
Pending to review now
