### ISSUE TITLE
Dark mode tooltip

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#33]
1. Bug title: Dark mode tooltip
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect bridge to your MM wallet
   - Start transfer
   - Confirm transfer in MM wallet
   - In 'My Pending Transactions' click on ! tooltip
6. Actual result: Light mode
7. Expected result: Dark mode

![image (1)](https://user-images.githubusercontent.com/88747529/134746405-aaa94c5e-6750-468b-9049-077a6e30d172.png)

**Comment by german-schneck** [comment]
Pending new revision

**Comment by QAPanda** [comment]
:white_check_mark:
