### ISSUE TITLE
Same status tooltip for each network 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#34]
1. Bug title: Same status tooltip for each network 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect bridge to your MM wallet
   - Start transfer
   - Confirm transfer in MM wallet
   - In 'My Pending Transactions' click on 'Processing !' tooltip
6. Actual result: Same status notice for all networks
![image](https://user-images.githubusercontent.com/88747529/134746889-c76c1bcf-61e9-47b6-9f86-a71fe9bdcd84.png)
7. Expected result: 
![image](https://user-images.githubusercontent.com/88747529/134746759-8a1369af-a555-4a82-b2b6-423a4a6bc7b5.png)

**Comment by german-schneck** [comment]
Pending new revision

**Comment by QAPanda** [comment]
:white_check_mark:
