### ISSUE TITLE
Responsive issues 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#35]
1. Bug title: Responsive issues 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Resize browser to 920x720
6. Actual result: 
<img width="882" alt="image-20210924205535731" src="https://user-images.githubusercontent.com/88747529/134747217-f1cdda55-4e4d-4a1e-b38f-dff423fe7d37.png">
 
<img width="865" alt="image-20210924202613813" src="https://user-images.githubusercontent.com/88747529/134747313-3f02814b-bbec-403d-8b3c-bc3371c0b87c.png">

<img width="873" alt="image-20210924204022674" src="https://user-images.githubusercontent.com/88747529/134747276-a75c13c0-8786-4d7a-b10e-73666c5eb8cd.png">

**Comment by QAPanda** [comment]
Resize browser to 650x720
Move to the bottom

![image](https://user-images.githubusercontent.com/88747529/136032383-ad29e2f9-778a-46c4-879b-0ec2f57029fa.png)

**Comment by german-schneck** [comment]
Ready for testing.

**Comment by QAPanda** [comment]
Issue moved to UI/UX ToDo list.
