### ISSUE TITLE
Add network icon

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#36]
1. Bug title: Add network icon
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM wallet 
   - See active network (top right)
6. Actual result: Missing network icon
<img width="336" alt="image-20210924205719497" src="https://user-images.githubusercontent.com/88747529/134747619-ed3c42f9-30ef-4122-8d2a-f903e741f178.png">
7. Expected result:

![image-20210924205755858](https://user-images.githubusercontent.com/88747529/134747639-07eb9558-b6fd-4f91-a83d-2f405a97f8ac.png)

**Comment by german-schneck** [comment]
Fixed!

**Comment by QAPanda** [comment]
:white_check_mark:
