### ISSUE TITLE
Loop on MAX amount

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#38]
1. Bug title: Loop on MAX amount
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.29.81 Chromium: 93.0.4577.82 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM wallet
   - Start transfer from BSC Testnet to Rinkeby (MAX amount > 2,000)
   - Confirm transfer
   - Switch to Rinkeby 
   - Click Claim
   - Confirm transfer 
6. Actual result:  Transfer is successful; balances are updated but bridge ends up in a loop
![image](https://user-images.githubusercontent.com/88747529/134765922-d5ac26e9-10b2-4725-a3ac-1fad2ea388aa.png)
7. Expected result: 
![image](https://user-images.githubusercontent.com/88747529/134765872-f7d16504-2448-4cc7-aa71-ae0eec66bae2.png)

**Comment by german-schneck** [comment]
Pending new revision.

**Comment by QAPanda** [comment]
:white_check_mark:
