### ISSUE TITLE
Light mode issues 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#39]
URL: http://bridgetest.zignaly.com/
OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
1. Hard to see text
![image](https://user-images.githubusercontent.com/88747529/135772716-a0f12089-29df-4245-8233-9bae44cd4b0c.png)
2. Hard to see 'CONVERT' button
![image](https://user-images.githubusercontent.com/88747529/135772780-588d5074-3d36-4831-a3af-c751079e64a8.png)
3. Hard to see loading
![image](https://user-images.githubusercontent.com/88747529/135772829-d2397bd6-b904-48ed-a8ba-d346d8821d42.png)

**Comment by QAPanda** [comment]
Approve button: 
![image](https://user-images.githubusercontent.com/88747529/135928535-d706efc5-2b68-420b-808d-88eeb97b2705.png)

**Comment by german-schneck** [comment]
Fixed

**Comment by QAPanda** [comment]
:white_check_mark:
