### ISSUE TITLE
Status tooltip does not open modal on click

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#40]
1. Bug title: Status tooltip does not open modal on click
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash:  -
4. OS/Browser version: 
   - OS: macOS Big Sur / Version 11.6
   - Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect MM wallet
   - Start transfer
   - See 'My Pending Transactions'
   - Resize to 520x702 (or mobile screen size)
6. Actual result:  Status tooltip does not open modal on click
![image](https://user-images.githubusercontent.com/88747529/135773158-d679de33-edf7-4f4c-9e62-923a7aaf5501.png)
7. Expected result: Open modal 
Example:
![image](https://user-images.githubusercontent.com/88747529/135773200-14ff37f7-a368-4e67-a4fb-f14eb4d68259.png)

**Comment by german-schneck** [comment]
Fixed!

**Comment by QAPanda** [comment]
:white_check_mark:
