### ISSUE TITLE
Approve loop

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#42]
1. Bug title: Approve loop
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: https://rinkeby.etherscan.io/tx/0x5d3349cdbd69a68f6e0cc618b73401baecd2503437c3567f4fecf2866630c1e9
4. OS: macOS Big Sur / Version 11.6 
   Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open http://bridgetest.zignaly.com/
   - Connect to MM wallet
   - Networks: Rinkeby (from chain); BSC Testnet (to chain)
   - Insert amount to start transfer Rinkeby >> BSC 
   - Click 'Approve' button
   - Confirm Rinkeby approval in MM wallet
   - Click 'Convert` button
   - Confirm transaction in MM wallet
   - Switch network to BSC
   - Click 'Claim' 
   - Confirm transaction in MM wallet (without approving it first)
6. Actual result: Ends up in a loop; the transaction is successful and balance is updated but 'APPROVE' loops until you reload the page
![image](https://user-images.githubusercontent.com/88747529/136012734-9debf4bd-1d1c-4390-8ba1-803c34d4e55b.png)
7. Expected result: Active 'APPROVE' button (since spending needs approval, not claiming)

**Comment by german-schneck** [comment]
Can you share me a screen record of the issue? Thank!

**Comment by QAPanda** [comment]
Record: https://www.dropbox.com/s/tniaqh1dkimocbt/approve-loop.mov?dl=0

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
Verified :white_check_mark:
