### ISSUE TITLE
Blank page on unsupported network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#43]
1. Bug title: Blank page on unsupported network
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS: macOS Big Sur / Version 11.6
   Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open:  http://bridgetest.zignaly.com/
   - Connect MM wallet
   - In MM wallet switch network to Ropsten Testnet (or any unsupported network)
6. Actual result: Blank page and TypeError
![image](https://user-images.githubusercontent.com/88747529/136198743-979f9d9f-48de-45f1-bd90-ddb58b8114d4.png)
![blank-page](https://user-images.githubusercontent.com/88747529/136199252-a107a3bd-c3ef-447e-a74d-ed8134e9e063.gif)
7. Expected result: Connect Wallet page

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
