### ISSUE TITLE
Balance is not updated after you switch network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#44]
1. Bug title: Balance is not updated after you switch network 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS: macOS Big Sur / Version 11.6
   Browser: Brave / Version 1.30.87 Chromium: 94.0.4606.71 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open:  http://bridgetest.zignaly.com/
   - Connect MM wallet
   - Switch network form Rinkeby to Polygon Testnet 
6. Actual result: Rinkeby network balance 
![image](https://user-images.githubusercontent.com/88747529/136206792-eee09d22-44a2-42f4-9887-e486a87a7846.png)
7. Expected result: Polygon balance

**Comment by german-schneck** [comment]
Ready for test.

**Comment by QAPanda** [comment]
:white_check_mark:
