### ISSUE TITLE
CLAIM button is available after transfer is confirmed in MM

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#45]
1. Bug title: CLAIM button is available after transfer is confirmed in MM
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Brave: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM 
   - Switch network to BSC Testnet
   - Start transfer from BSC Testnet to Rinekeby
   - Confirm transfer in MM wallet
   - Switch network to Rinkeby (when ready)
   - Click CLAIM button
   - Confirm transfer in MM wallet
   - Click CLAIM button
   - Confirm transfer in MM wallet
   - Click CLAIM button
   - Confirm transfer in MM wallet
6. Actual result: CLAIM button is available after transfer is confirmed in MM 
7. Expected result:  Spinner after confirm in MM (not possible to CLAIM two times)

Video: https://www.dropbox.com/s/jotwzh0qtkat235/CLAIM.mov?dl=0

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
Verified :white_check_mark:

**Comment by QAPanda** [comment]
Uploading Screen Recording 2021-11-24 at 7.47.18 PM.mov…

**Comment by QAPanda** [comment]
https://user-images.githubusercontent.com/88747529/143298305-c0712f54-7933-467a-8089-e33a4c5d3712.mov
