### ISSUE TITLE
Loop on switch network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#46]
1. Bug title: Loop on switch network
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Brave: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM 
   - Start transfer from Rinkeby to BSC Testnet
   - Confirm transfer in MM wallet
   - Switch network to Polygon Mumbai Testnet
6. Actual result: CONVERT NOW button loops; amount doesn't reset
7. Expected result: Available CONVERT NOW option; resets amount once transaction is confirmed and in MPT

Record: https://www.dropbox.com/s/xsvzl1byheolmkz/switch-loop.mov?dl=0

And if you keep switching networks you will get blank page and Internal Server Error
Record: https://www.dropbox.com/s/jqb8hr9obatukf0/switch-error.mov?dl=0

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
Verified :white_check_mark:
