### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#47]
1. Bug title: Internal Server Error
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Brave: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM 
   - Start transfer from Rinkeby to BSC Testnet (39,000)
   - Confirm transfer in MM wallet
   - Switch network to BSC Testnet
   - Start transfer from BSC Testnet to Rinkeby (MAX)
   - Confirm transfer in MM wallet
   - Claim transfer (39,000)
   - Confirm transfer in MM wallet
6. Actual result: Internal Server Error
7. Expected result: Successful transfers without errors

Record: https://www.dropbox.com/s/nn5lo46k3lasdmu/internal-server-error.mov?dl=0

**Comment by QAPanda** [comment]
Same error on POYI
Steps to reproduce: 
   - Switch network to Polygon Mumbai Testnet
   - Start transfer from Polygon Mumbai Testnet to BSC Testnet
   - Confirm transfer in MM wallet
   
Record: https://www.dropbox.com/s/w5oun938fjxvzux/poly-bsc.mov?dl=0

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
Verified :white_check_mark:
