### ISSUE TITLE
Convert button loop (BSC >> POLY)

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#48]
1. Bug title: Convert button loop
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Brave: Version 1.30.89 Chromium: 94.0.4606.81 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open: http://bridgetest.zignaly.com/
   - Connect to MM 
   - Switch network to BSC Testnet
   - Start transfer from BSC Testnet to Polygon Mumbai Testnet
   - Confirm transfer in MM wallet
   - Switch network to Polygon Mumbai Testnet
   - Claim transfer 
   - Confirm transfer in MM wallet
6. Actual result: Convert button keeps looping after transfer is done
![image](https://user-images.githubusercontent.com/88747529/137040755-11932cfc-4906-4eee-969b-3839b58d2ae9.png)
7. Expected result:  Available CONVERT NOW option; resets amount once transaction is confirmed

**Comment by german-schneck** [comment]
I have repaired a bug that did just this, confirm it too.
https://github.com/zignaly-open/zignaly-open-bridge/issues/46

**Comment by QAPanda** [comment]
Verified :white_check_mark:
