### ISSUE TITLE
MM RPC error: "header not found"

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#51]
1. Bug title: "header not found"
2. URL: http://bridge.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Chrome: Version 95.0.4638.54 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Chrome open:  http://bridge.zignaly.com/
   - Click 'Connect Wallet' button
   - Pick MM and confirm connection in MM wallet
6. Actual result: MM RPC error "header not found", and approve button even if an account is already approved 

https://user-images.githubusercontent.com/88747529/138454279-701c3eb9-9618-4204-917c-1dd0fdc9b120.mov

**Comment by german-schneck** [comment]
Any update for this issue?

**Comment by QAPanda** [comment]
It is production issue.
