### ISSUE TITLE
Missing claim/switch network button

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#52]
1. Bug title: Missing claim/switch network button
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6 /
   Chrome: Version 95.0.4638.54 (Official Build) (x86_64)
5. Steps to reproduce: 
https://user-images.githubusercontent.com/88747529/138455013-21b982c6-7a09-4167-8229-559c3d632eee.mov
6. Actual result: Missing claim/switch network button
7. Expected result: Available claim/switch network button

**Comment by german-schneck** [comment]
Try this error again, if it happens again tell me.

**Comment by QAPanda** [comment]
:white_check_mark:
