### ISSUE TITLE
Program log: BridgeError => Nonce 16 in ChainId 4 is processed yet

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#53]
1. Bug title: Program log: BridgeError => Nonce 16 in ChainId 4 is processed yet
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: https://rinkeby.etherscan.io/tx/0x52a7419ba08450e9bfcfa925c51e66ae777ed9dbaa708262e847cfafcb631672
https://explorer.solana.com/tx/2CUVmMApe1TCsgwSjqQLKWkirUtcXk6xijixXXatv72ALztAqRaZMqFyN25z5qLggcAuypYFbubHDDbS2K5diEYE?cluster=devnet
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - In Brave open:  http://bridgetest.zignaly.com/
   - Connect MM wallet
   - Switch fromChain network to Rinkeby
   - Switch toChain network to Solana 
   - Connect Phantom wallet
   - Start transfer
   - Confirm transfer in MM 
6. Actual result: Successful transfer but error in pm2 log
   Program log: BridgeError => Nonce 16 in ChainId 4 is processed yet
7. Expected result: Successful transfer without errors

Note: Same for BSC>>SOL and POLY>>SOL

**Comment by german-schneck** [comment]
Jorge told me that this is solved, have you reproduced it again?

**Comment by QAPanda** [comment]
Yes, I sent record with pm2 log in Slack.

**Comment by german-schneck** [comment]
I can't find the log, could you pass it here?

**Comment by QAPanda** [comment]
pm2 log:
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
Program log: Checking full_nonce => 4_114
Program log: Added to the bridge => Nonce 114 in ChainId 4
Program consumed 466 of 466 compute units
Program failed to complete: exceeded maximum number of instructions allowed (466) at instruction #11724

And processing loop:

https://user-images.githubusercontent.com/88747529/144238198-fba55eea-e019-4ee8-993f-7aa52528329e.mov

**Comment by QAPanda** [comment]
:white_check_mark:
