### ISSUE TITLE
SOL balance is not updating after the transfer is done

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#55]
1. Bug title: SOL balance is not updating after the transfer is done
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - Switch fromChain network to Rinkeby
   - Switch toChain network to Solana
   - Start transfer
   - Confirm transfer in MM 
6. Actual result: The transfer is successful but SOL balance is not updated 
7. Expected result: All balances updated 

https://user-images.githubusercontent.com/88747529/140990363-b0afb012-5473-43bd-a091-55a358e3d7cc.mov

Note: Same for POLY >> SOL

**Comment by german-schneck** [comment]
It works for me, it just takes a while.

**Comment by QAPanda** [comment]
I can not test it due to this issue: https://github.com/zignaly-open/zignaly-open-bridge/issues/53#issuecomment-983618756

**Comment by QAPanda** [comment]
:white_check_mark:
