### ISSUE TITLE
BSC >> SOL - Processing loop 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#56]
1. Bug title: BSC >> SOL - Processing loop 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - Switch fromChain network to BSC
   - Switch toChain network to Solana
   - Start transfer
   - Confirm transfer in MM 
6. Actual result: Transfer is successful, SOL balance is updated but loop in UI
7. Expected result: Successful transfer without loop

![image](https://user-images.githubusercontent.com/88747529/140994220-44900397-2f67-4860-8714-f3105da5498a.png)

https://user-images.githubusercontent.com/88747529/140993861-a7b4b032-46e5-47ca-9af2-96f23105d0a7.mov

**Comment by german-schneck** [comment]
Can you send me test zigcoins?

**Comment by german-schneck** [comment]
It looks like it's the provider, could you please send me the log of the bridge at the time of the conversion?

**Comment by QAPanda** [comment]
Related to issue https://github.com/zignaly-open/zignaly-open-bridge/issues/53
