### ISSUE TITLE
Zero balance after reconnection

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#57]
1. Bug title: Zero balance after reconnection
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - Disconnect from the bridge (using disconnect button)
   - Open MM and disconnect bridge 
   - Refresh page
   - Connect MM again 
6. Actual result: Zero balance
7. Expected result: Update balances after reconnection 

https://user-images.githubusercontent.com/88747529/140996854-c98e519f-139f-494c-9d3b-783f0e768af0.mov

**Comment by german-schneck** [comment]
The video is from an older version of the app, please could you reconfirm this issue?

**Comment by QAPanda** [comment]
Here are new steps, but old are also valid:
- disconnect using disconnect button
- connect again
https://user-images.githubusercontent.com/88747529/143464697-ab4ff0cd-1224-4fc9-ac34-a136ed20f6dc.mov
