### ISSUE TITLE
NETWORK_ERROR

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#59]
1. Bug title: NETWORK_ERROR
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - Open MM and switch to Ethereum Mainnet
6. Actual result: NETWORK_ERROR

![image](https://user-images.githubusercontent.com/88747529/140998627-42679589-e089-498b-b76e-e24030024de0.png)

https://user-images.githubusercontent.com/88747529/140998493-65aa4532-34a1-45d6-970b-1ae041043c03.mov

**Comment by QAPanda** [comment]
![image](https://user-images.githubusercontent.com/88747529/142182673-95d1fa8c-785a-4cff-b75f-6aae80b5510f.png)

**Comment by german-schneck** [comment]
I have set a filter that does not allow errors to be displayed. However, the network will not be established until there is a token and bridge address.
