### ISSUE TITLE
Loop on switch network

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#64]
1. Bug title: Loop on switch network
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.31.88 Chromium: 95.0.4638.69 (Official Build) (x86_64)]
5. Steps to reproduce: 
   - Switch fromChain to Rinkeby 
   - Switch toChain to Solana
   - Start transfer
   - Confirm transfer in MM
   - Switch network to BSC
6. Actual result: Loop
7. Expected result: Possible to start new transfer 

https://user-images.githubusercontent.com/88747529/141010201-e8c4ac22-c3c7-48bc-ae1e-044010389731.mov

**Comment by QAPanda** [comment]
Transaction was successful, balance is updated but transaction keeps looping i UI
![image](https://user-images.githubusercontent.com/88747529/141010674-97138962-6d8a-45cd-b7f9-86f49352c949.png)

Also in DB is in processing state
![image](https://user-images.githubusercontent.com/88747529/141010813-2c431976-0fb8-4adc-85f7-456326c84a07.png)

**Comment by QAPanda** [comment]
Not related to network:

https://user-images.githubusercontent.com/88747529/144244373-fa71e272-dd6d-48cb-8760-cb0eeeca8768.mov

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
