### ISSUE TITLE
Rinkeby network on both sides 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#68]
1. Bug title: Rinkeby network on both sides 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - fromChain network is BSC
   - toChain network is Rinkeby
   - In MM wallet switch network to Kovan Test Network
   - In MM wallet switch network to Rinkeby
6. Actual result: Rinkeby network selected on both sides
7. Expected result: Different networks in fromChain and toChain

https://user-images.githubusercontent.com/88747529/142186105-6e716692-d351-4a43-b055-afa64fe441e7.mov

**Comment by QAPanda** [comment]
It is even possible to start transfer from Rinkeby to Rinkeby:
![image](https://user-images.githubusercontent.com/88747529/142186421-7fbe63df-59e4-4c72-aebd-f18b9519cde5.png)


![image](https://user-images.githubusercontent.com/88747529/142186660-c9256bce-322c-482d-aac8-18a961813887.png)


https://user-images.githubusercontent.com/88747529/142186522-c69f5a3a-108b-45b4-a357-8745d1495231.mov

**Comment by QAPanda** [comment]
:white_check_mark:

**Comment by german-schneck** [comment]
Check this again, I have made it throw an error when you switch to an invalid network.

**Comment by QAPanda** [comment]
Check this out:

https://user-images.githubusercontent.com/88747529/143479714-c89bfeed-6777-4523-849d-5342d88892a4.mov
