### ISSUE TITLE
No CLAIM button

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#69]
1. Bug title: No CLAIM button
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Switch fromChain network to Rinkeby ((not related to network)
   - Switch toChain network is BSC (not related to network)
   - Start transfer
   - Confirm transfer in MM wallet
   - Switch network to BSC
6. Actual result: No claim button (it is just looping)
7. Expected result: Claim button available

https://user-images.githubusercontent.com/88747529/142188762-71235538-9212-4e4f-8824-371b86be4729.mov

Note: If I reload the page, claim button will show up.

**Comment by german-schneck** [comment]
Can u retry now.
