### ISSUE TITLE
Phantom wallet is connected but UI offers `Connect Phantom Wallet` option

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#71]
1. Bug title: Phantom wallet is connected but UI offers `Connect Phantom Wallet` option
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - In Brave open http://bridgetest.zignaly.com/
   - Unlock and connect MM wallet
   - Unlock and connect Phantom wallet
   - Switch toChain network to SOL
   - Click `Connect Phantom Wallet` button
6. Actual result: Wallet is connected but UI offers `Connect Phantom Wallet` option 
7. Expected result: Wallet connected and SOL balance updated 

https://user-images.githubusercontent.com/88747529/142911162-912262c5-2213-4e82-80a3-6eca0d215dbc.mov

**Comment by german-schneck** [comment]
This is a technical capability of Phantom. It happens that the connection of the app wallet provider is independent of the state of the browser wallet. No matter how much you connect phantom in the extension, it will require you to access and initialise the provider within the app.

We'll see if it gives us more options in the future.

**Comment by QAPanda** [comment]
Connect Wallet button is not clickable:

https://user-images.githubusercontent.com/88747529/144240955-e7d4bdf7-0ffa-4b51-8216-954088cfab5d.mov


https://user-images.githubusercontent.com/88747529/144241393-daa94bea-0027-4d68-930d-1db59410b5da.mov

**Comment by german-schneck** [comment]
I cannot reproduce the problem.

The phantom button works fine, and when the wallet is connected when you reflash it still shows the convert button.
