### ISSUE TITLE
Switch issues

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#72]
1. Bug title: Switch issues
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - fromChain network to Rinkeby and toChain network is BSC
   - Switch toChain network to SOL
   - Switch fromChain network BSC
6. Actual result: toChain network is switched to Rinkeby 
7. Expected result: toChain network should be SOL

https://user-images.githubusercontent.com/88747529/142915852-52518066-ac5b-493e-9a74-f8b6d0812676.mov

**Comment by QAPanda** [comment]
Other weird cases:
https://user-images.githubusercontent.com/88747529/142916337-51bb167d-4c23-4846-adba-998f2c4cc9fc.mov

**Comment by german-schneck** [comment]
try now this issue :)

**Comment by QAPanda** [comment]
:white_check_mark:
