### ISSUE TITLE
Not possible to reconnect MM wallet after disconnect (using disconnect button) 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#74]
1. Bug title: Not possible to reconnect MM wallet after disconnect (using disconnect button) 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Switch toChain network to SOL
   - Connect Phantom Wallet (if not connected)
   - Click `Disconnect` button 
   - Reconnect MM wallet (click on `Connect Wallet` or `Connect MM Wallet` button)
6. Actual result: UI offers Phantom wallet instead MM wallet 
7. Expected result: 'Connect to your MM Wallet' option

https://user-images.githubusercontent.com/88747529/143120832-d55ebd58-440e-4829-8908-2fe8d5e8f162.mov

https://user-images.githubusercontent.com/88747529/143118208-9c9adf55-e3e7-4ddb-a293-cc860cbc80f7.mov

**Comment by german-schneck** [comment]
done, try it now

**Comment by QAPanda** [comment]
Fresh record (Firefox browser):

https://user-images.githubusercontent.com/88747529/143431085-4dbc7573-3e94-4f31-b777-a0ac80268a0b.mov

**Comment by QAPanda** [comment]
:white_check_mark:
