### ISSUE TITLE
Switch after reconnection

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#75]
1. Bug title: Switch after reconnection
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce: 
   - Disconnect from MM (using `Disconnect` button)
   - Switch toChain to SOL
   - Connect MM wallet
6. Actual result: toChin network is switched to BSC
7. Expected result: toChain network should be SOL

https://user-images.githubusercontent.com/88747529/144230510-e80c235f-3dfc-4946-b56f-b2d6d02e2f13.mov

**Comment by german-schneck** [comment]
Try again! @QAPanda it's fixed.

**Comment by QAPanda** [comment]
:white_check_mark:
