### ISSUE TITLE
Small delay in balance update 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#79]
1. Bug title: Small delay in balance update 
2. URL: http://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.1 /
   Brave Version 1.32.106 Chromium: 96.0.4664.45 (Official Build) (x86_64)
5. Steps to reproduce:
   - Switch fromChain network to SOL and toChain to BSC
   - Switch fromChain to BSC
   - Switch back to SOL
6. Actual result: Delay in SOL balance update (it shows BSC balance first, and after 3 sec. actual SOL balance)
7. Expected result: SOL balance

https://user-images.githubusercontent.com/88747529/144261737-3266d99e-1547-419f-9fd5-0c729002122a.mov

**Comment by german-schneck** [comment]
The delay depends entirely on the network at the time.
