### ISSUE TITLE
Possible error handling

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#81]
1. Specify which network is having problem in this error message:

![image](https://user-images.githubusercontent.com/88747529/144838794-8bc748b1-3d0c-4a40-86cd-62a61a4c41eb.png)

2. When you don’t have for gas, you don’t receive any message regarding the claiming the converted amount.
3. On mobile when you don’t have bsc or poly network, you can not switch, and don’t receive any message.

**Comment by german-schneck** [comment]
1. Done

**Comment by german-schneck** [comment]
3. Done.

**Comment by QAPanda** [comment]
#2 moved to UI/UX improvements - Slack list
