### ISSUE TITLE
Unstable balance (header balance)

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#82]
1. Bug title: Unstable balance (header balance)
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
   Brave Version Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)
5. Steps to reproduce:
   - Starting point
     - fromChain network is Rinkeby and toChain is BSC
     - Rinkeby balance is 50,000,000, and BSC balance is 0
   - Switch fromChain to BSC
   - Look at BSC balance in header 
6. Actual result: Unstable balance (jumping between Rinkeby and BSC balance)
7. Expected result: BSC balance

https://user-images.githubusercontent.com/88747529/147289547-b054f3a4-88c1-4442-90c9-1fc988a05c9e.mov

**Comment by QAPanda** [comment]
https://user-images.githubusercontent.com/88747529/147289934-ae2e90a6-93c7-4772-8319-426b3a7bd34a.mov

**Comment by german-schneck** [comment]
Done, check this now 👍🏻

**Comment by QAPanda** [comment]
:white_check_mark:
