### ISSUE TITLE
fromChain network changes from Solana to Rinkeby after connecting MM

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#83]
1. Bug title: fromChain network changes from Solana to Rinkeby after connecting MM
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
   Brave Version Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)
5. Steps to reproduce:
   - Starting point
     - fromChain network is SOL and toChain is POLY (or any MM network)
     - MM is in disconnected state
   - Click Connect MM Wallet button and connect MM wallet
6. Actual result: fromChain network changes to Rinkeby (or other connected network)
7. Expected result: fromChain network is Solana

https://user-images.githubusercontent.com/88747529/147341798-c7cb601b-5edb-4301-baf5-ba869ab022b6.mov

**Comment by QAPanda** [comment]
Note that SOL balance is 0 even if Phantom wallet is connected.

**Comment by german-schneck** [comment]
Test the network changes. I am still looking at the balance problem.

**Comment by QAPanda** [comment]
:white_check_mark:
