### ISSUE TITLE
Bridge is not updating after changing Phantom wallet account

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#84]
1. Bug title: Bridge is not updating after changing Phantom wallet account
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
   Brave Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)
5. Steps to reproduce:
   - Requirements 
     - Create at least 2 accounts in Phantom wallet
   - Connect Phantom wallet to bridge 
   - Switch account in Phantom wallet
6. Actual result: SOL balance and address are not updating 
7. Expected result: Bridge updates with new acc. details 

https://user-images.githubusercontent.com/88747529/147341936-fbf2eefb-f63c-41f0-b6f8-20d74525e5dc.mov

**Comment by german-schneck** [comment]
There is a technical limitation in that the library does not currently support listening for wallet changes.

However, this is pending review and implementation in the future.

Here are the links:

Issue:
https://github.com/solana-labs/wallet-adapter/issues/49

Pull-Request from GitHub.
https://github.com/solana-labs/wallet-adapter/pull/109

**Comment by QAPanda** [comment]
Could you check this out: https://stackoverflow.com/questions/69973752/detecting-on-the-browser-when-user-switches-phantom-wallet-accounts

**Comment by QAPanda** [comment]
Temp. solution: disconnect wallet
