### ISSUE TITLE
UI/UX - Landing page state: both wallets disconnected 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#85]
If both wallets (MM and Phantom) are disconnected page should look as in the pic. below:

![Image from iOS](https://user-images.githubusercontent.com/88747529/147343334-6076435e-fc7a-401e-808b-26167551b491.jpg)

**Comment by german-schneck** [comment]
Done.

**Comment by QAPanda** [comment]
:white_check_mark:
