### ISSUE TITLE
UI/UX Improvements

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#86]
1. Change `Connect Wallet` to `Connect Solana Wallet` and add SOL icon
![image](https://user-images.githubusercontent.com/88747529/147359885-a90859a2-a59a-4ed8-82fd-93e72397bcb4.png)

Design:
![image](https://user-images.githubusercontent.com/88747529/147359935-789f3a98-7d86-4073-8fa5-7a1abc7ba059.png)

Same for MM: `Connect MetaMask Wallet`

**Comment by QAPanda** [comment]
2. Add SOL icon and some extra space
![image](https://user-images.githubusercontent.com/88747529/147360139-4747c66f-67c9-4015-ad70-9f6aa7691080.png)

Design: 
![image](https://user-images.githubusercontent.com/88747529/147360160-91107004-fe36-431d-b623-140243e3e6de.png)

**Comment by QAPanda** [comment]
3. Add some space as in design

![image](https://user-images.githubusercontent.com/88747529/147360230-1b7933c3-b939-4131-b8f2-1891d5624460.png)

Design:
![image](https://user-images.githubusercontent.com/88747529/147360286-298f8c02-6960-4f68-927e-e8aef412b2bb.png)

**Comment by QAPanda** [comment]
4. Increase spacing between letters

**Comment by QAPanda** [comment]
5. Use #4cbabc for Solana aqua text

**Comment by QAPanda** [comment]
4. Update BSC logo
![image](https://user-images.githubusercontent.com/88747529/147360522-e24a10c6-e781-4d85-8169-caf1287aabd3.png)

**Comment by german-schneck** [comment]
I have uploaded the changes and fixes for this.

You can change the BSC icon from the database, upload it to imgur or some file hosting provider and paste the URL in the "image" field of the chain table.

**Comment by QAPanda** [comment]
1 :white_check_mark:
2 :white_check_mark:
4 :white_check_mark:

**Comment by QAPanda** [comment]
5. Missing SOL processing tooltip 
![image](https://user-images.githubusercontent.com/88747529/147561265-c1fceccb-6bf8-4d49-af7e-d2b02f85f07c.png)

Text: Transaction awaiting confirmation on Solana. This usually takes around 15 seconds. If it's taking too long, try increasing the gas or cancelling the transaction in your wallet.

Also, Polygon tooltip text should be: Transaction awaiting confirmation on Polygon. This usually takes around 15 seconds. If it's taking too long, try increasing the gas or cancelling the transaction in your wallet.

**Comment by QAPanda** [comment]
6. Round balances to 4 decimals
![image](https://user-images.githubusercontent.com/88747529/147577745-be87919d-2e9f-4f5a-8fd1-c3aa1acc095e.png)

![image](https://user-images.githubusercontent.com/88747529/147577787-46ed8713-5043-4df0-8c83-f709b79922e1.png)

7. Round amount in MPT to 4 decimals
![image](https://user-images.githubusercontent.com/88747529/147577906-ce16bdae-7719-4e5c-972f-5fb0dbfdc875.png)


!!Note that user still should be able to insert full amount by typing or pressing MAX. Rounding on balance and MPT is just visual thing.

**Comment by QAPanda** [comment]
7. Missing network icon on 'Switch' button

![image](https://user-images.githubusercontent.com/88747529/148534360-9c3c4f5b-443c-4390-b5c1-7bd81ac7d9ce.png)

![image](https://user-images.githubusercontent.com/88747529/148535157-5de2474b-3aae-43cb-965b-96660ded690e.png)

**Comment by QAPanda** [comment]
8. Responsiveness (630x714)
![image](https://user-images.githubusercontent.com/88747529/148534744-c24d19eb-bdf3-4af3-bc8d-0355f9a526bf.png)

**Comment by QAPanda** [comment]
Clean version here: https://github.com/zignaly-open/zignaly-open-bridge/issues/91
