### ISSUE TITLE
Error handling - FE msg

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#87]
1. When you don’t have for gas, you don’t receive any message regarding the claiming the converted amount.

**Comment by QAPanda** [comment]
2. FE msg if pending request in MM.
<img width="1427" alt="image-20211209195438360" src="https://user-images.githubusercontent.com/88747529/147562393-f39ecf24-3800-4d64-ae91-053ade9d83b8.png">

**Comment by QAPanda** [comment]
3. FE msg: You must connect your MetaMask wallet to continue.

https://user-images.githubusercontent.com/88747529/149568831-6bb0b1cf-d908-41de-8a25-d01d07e3f916.mov

SOL:

https://user-images.githubusercontent.com/88747529/149592976-d4661509-e84f-480f-acc3-7a8bc513f37b.mov

**Comment by german-schneck** [comment]
3. Done

**Comment by QAPanda** [comment]
3 :white_check_mark:

**Comment by QAPanda** [comment]
2 is ok now, since we do not have pending request in MM. 
MetaMask - RPC Error: User rejected the request.
Request is rejected so you can request switch again.
