### ISSUE TITLE
Color spec mismatch - light mode

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#88]
1. Connect Wallet button 	

Spec:
border => #6a4dd1 // rgb(106, 77, 209)
text and icon => #5b3ccc // rgb(91, 60, 204)

![image](https://user-images.githubusercontent.com/88747529/147674050-8e050ae6-d26f-41f7-81c7-44ef2fbc21c7.png)

**Comment by QAPanda** [comment]
2. Help tooltip

Spec:
tooltip => #6065c4 // rgb(96, 101, 196)	      
text => #808080 // rgb(128, 128, 128)	
letter-spacing: 1px;

![image](https://user-images.githubusercontent.com/88747529/147674129-65709521-b874-45e4-8d77-6604657fa125.png)

**Comment by QAPanda** [comment]
3. Convert ZIG text

Spec:
#FFFFFF // rgb(255, 255, 255)
letter-spacing: 1px;	
https://codepen.io/transitori/pen/KKqGggP

![image](https://user-images.githubusercontent.com/88747529/147674252-260e9350-7c2c-4058-8a16-1e2cc1778054.png)

**Comment by QAPanda** [comment]
4. Box

Spec:
bg => #dfdff6 // rgb(223, 223, 246)
increase font to 17px
https://codepen.io/transitori/pen/KKqGggP
.field {
      background: #dfdff6;
      color: #6067c8;
      padding: 20px;
      margin: 20px 15px;
      border-radius: 7.5px;
      font-size: 17px;
    }

![image](https://user-images.githubusercontent.com/88747529/147674863-92217236-4211-40a1-9b8d-b44cdd99d54d.png)

**Comment by QAPanda** [comment]
5. Box bg

Spec:
https://codepen.io/transitori/pen/KKqGggP 

.box {
      background: #7b8ed1;
      background-image: linear-gradient(140deg, #817cce, #779fd4);
      box-shadow: 0px 0px 14px #bbb;
      margin: 25px 10px;
      padding: 35px 15px 10px;
      color: #fff;
      border-radius: 15px;
      width: 365px;
      text-align: center;
      display: inline-block;
    }
 


![image](https://user-images.githubusercontent.com/88747529/147675162-48bc168a-f8bd-4dcd-b5cd-2d0d2a08bd8f.png)

**Comment by QAPanda** [comment]
6. Header balance
Spec:
balance => #4b4978 // rgb(75, 73, 120)		   	
bg => #ede4f9 // rgb(237, 228, 249)	 						   
letter-spacing: 1px;

![image](https://user-images.githubusercontent.com/88747529/147691357-c0dbc5a1-cd99-406c-b850-4ccab52cdcd5.png)

**Comment by QAPanda** [comment]
7. Amount/receive
Spec: 
amount/receive => #fff //rgb(255, 255, 255)

![image](https://user-images.githubusercontent.com/88747529/147692284-86c0ca69-693b-41df-9ef5-2d492ed7b6a9.png)

**Comment by QAPanda** [comment]
8. ETH amount
Spec:
https://codepen.io/transitori/pen/KKqGggP
    .amount {
      color: #555dcf;
      font-size: 38px;
      font-weight: 500;
    }

![image](https://user-images.githubusercontent.com/88747529/147692779-f4d56a5d-5d2e-4790-a290-75ebdba8cced.png)

**Comment by QAPanda** [comment]
9. Max button
Spec:
#555dcf // rgb(85, 93, 207)	

![image](https://user-images.githubusercontent.com/88747529/147693225-17f231d5-11c6-48fa-96f6-d9cc03765ce1.png)

**Comment by QAPanda** [comment]
10. ETH balance
Spec:
#eaebff // rgb(234, 235, 255)
letter-spacing: 1px;

![image](https://user-images.githubusercontent.com/88747529/147693933-5ba7e2b5-0058-4525-9b1c-2b7d6069bc70.png)

**Comment by QAPanda** [comment]
11. BSC text and logo
Spec:
#cd9442 // rgb(205, 148, 66)
#edbb53 // rgb(237, 187, 83)

![image](https://user-images.githubusercontent.com/88747529/147696051-a8f85987-87a3-4f19-831f-44f0c09b7c0a.png)

**Comment by QAPanda** [comment]
12. Letter spacing 
letter-spacing: 1px;

![image](https://user-images.githubusercontent.com/88747529/147739628-8ff28256-e83d-4884-bd99-03c50beed149.png)

**Comment by QAPanda** [comment]
13. BSC amount
Specs:
https://codepen.io/transitori/pen/KKqGggP
  .box.bsc .amount {
      color: #fdecc8;
    }

![image](https://user-images.githubusercontent.com/88747529/147740390-26d81134-3581-47eb-8a01-086ce0b59df5.png)

**Comment by QAPanda** [comment]
14. ZIG on receive side
Spec:
#f3f4f6 // rgb(243, 244, 246)	

![image](https://user-images.githubusercontent.com/88747529/147740750-b274a0a2-cb4b-4bd4-a1ea-80814c889c05.png)

**Comment by QAPanda** [comment]
15. BSC balance
Spec:
  .box.bsc .amount {
      color: #fdecc8;
    }

![image](https://user-images.githubusercontent.com/88747529/147741053-ff167114-bd4e-4cb6-be08-50d58a5c3eb0.png)

**Comment by QAPanda** [comment]
16. Convert now button
increase font to 15px
background-image: linear-gradient(120deg, #7569de, #41bdd8);

https://codepen.io/transitori/pen/KKqGggP
.mainbutton {
      color: #FFF;
      text-transform: uppercase;
      font-size: 15px;
      letter-spacing: 2px;
      font-weight: 500;
      background: #6b79dd;
      background-image: linear-gradient(120deg, #7569de, #41bdd8);
      margin: 0px auto;
      padding: 17px 35px;
      border-radius: 7px;
      display: inline-block;
      clear: both;
    }

![image](https://user-images.githubusercontent.com/88747529/147741367-e554ae9e-13ef-4a44-b5c4-6a1fb180dbae.png)

**Comment by QAPanda** [comment]
17. Approve box
- letter-spacing: 1px;
- "First time conversion..." text should not be bold
- Missing ! tooltip

![image](https://user-images.githubusercontent.com/88747529/147742027-a4617997-f5c7-47f6-838b-3730a8f805c1.png)
![image](https://user-images.githubusercontent.com/88747529/147742200-26920689-1d51-45da-a0e2-e8faecb1eaad.png)

**Comment by QAPanda** [comment]
18. Poly colors
- text color 
- amount color
- balance color
![image](https://user-images.githubusercontent.com/88747529/147742639-15a02d8d-bb78-4ae6-8c7e-cb398376b32f.png)

**Comment by QAPanda** [comment]
19. Sol colors

![image](https://user-images.githubusercontent.com/88747529/147742905-d04f4288-0d3c-4b8a-8e90-242a053cadf8.png)

**Comment by QAPanda** [comment]
20. MPT
![image](https://user-images.githubusercontent.com/88747529/147747265-221680e0-e944-4b04-957b-5d4bd2bfc2ef.png)

**Comment by QAPanda** [comment]
1 :white_check_mark:
2 :white_check_mark:
3 :white_check_mark:
4 :white_check_mark:
6 :white_check_mark:
7 :white_check_mark:
8 ok except font-weight: 500;
10 ok except letter-spacing: 1px;
11 :white_check_mark:
12 :white_check_mark:
13 need to check what is right color for fromChain side (for all networks)
14 :white_check_mark:

**Comment by german-schneck** [comment]
To review:

8. Done
9. Done
10. Done
15. Done
16. Done
17. Done
18. Done
19. Done

**Comment by QAPanda** [comment]
8 :white_check_mark:
9 :white_check_mark:
10 :white_check_mark:
11 :white_check_mark:
12 :white_check_mark:
13 need to check what are right colors for fromChain side for BSC/POLY/SOL, and for toChain side for ETH
14 :white_check_mark:
15 :white_check_mark:
16 :white_check_mark:
17 :white_check_mark:
18 :white_check_mark:
19 :white_check_mark:

**Comment by QAPanda** [comment]
20 three minor things
![image](https://user-images.githubusercontent.com/88747529/148855630-ba006b2e-5ff1-44f9-9607-72569f574ae5.png)
