### ISSUE TITLE
SOL balance in header is not updating after transfer is done

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#89]
1. Bug title: SOL balance in header is not updating after transfer is done
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
   Brave Version Version 1.33.106 Chromium: 96.0.4664.110 (Official Build) (x86_64)
5. Steps to reproduce:
   - Start transfer from BSC to SOL (not related to network)
   - Confirm transfer in MM
   - Wait for transfer to be processed 
6. Actual result: SOL balance in header is not updating 
7. Expected result: SOL balance updates 

https://user-images.githubusercontent.com/88747529/148533896-9bb01103-cab8-49d6-af77-460671695d6a.mov

**Comment by german-schneck** [comment]
Try this now!

**Comment by QAPanda** [comment]
:white_check_mark:
