### ISSUE TITLE
Error: call revert exception; Internal problem

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#90]
1. Bug title: Error: call revert exception; Internal problem
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
   Chrome Version 97.0.4692.71 (Official Build) (x86_64)
5. Steps to reproduce:
   - Disconnect MM from the bridge (using `Disconnect this account` in MM wallet)
   - Clean cache and refresh page
   - Click `Connect MM wallet` button
   - Pick account and confirm connection in MM wallet  
6. Actual result: Error: call revert exception; Internal problem
7. Expected result: Connect MM wallet to bridge

https://user-images.githubusercontent.com/88747529/148838260-48f7b74d-9f7c-4ca4-b455-64f6edb4af7e.mov

**Comment by QAPanda** [comment]
Same with bridge disconnect button:

https://user-images.githubusercontent.com/88747529/149025092-bd45090d-03aa-4300-bc89-4a93bc89c0e7.mov

**Comment by german-schneck** [comment]
Try it now.

**Comment by QAPanda** [comment]
:white_check_mark:
