### ISSUE TITLE
UI/UX Improvements (clean)

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#91]
1.  Missing network icon on 'Switch' button

![image](https://user-images.githubusercontent.com/88747529/148844300-3fbc7eb2-6828-4df2-9ebd-d18cf9c7b6d1.png)

![image](https://user-images.githubusercontent.com/88747529/148535157-5de2474b-3aae-43cb-965b-96660ded690e.png) 

2. Missing network name after switch (transfer SOL >> Rinkeby/BSC/POLY)

![image](https://user-images.githubusercontent.com/88747529/148844554-110bef1f-69d9-4945-83f1-22aa69c29112.png)

https://user-images.githubusercontent.com/88747529/148844621-0efd47c5-12bb-44ae-9a77-3f48eb0e3e6f.mov

3. Missing SOL processing tooltip 
![image](https://user-images.githubusercontent.com/88747529/147561265-c1fceccb-6bf8-4d49-af7e-d2b02f85f07c.png)

Text: Transaction awaiting confirmation on Solana. This usually takes around 15 seconds. If it's taking too long, try increasing the gas or cancelling the transaction in your wallet.

Also, Polygon tooltip text should be: Transaction awaiting confirmation on Polygon. This usually takes around 15 seconds. If it's taking too long, try increasing the gas or cancelling the transaction in your wallet.

4. Round balances to 4 decimals
![image](https://user-images.githubusercontent.com/88747529/147577745-be87919d-2e9f-4f5a-8fd1-c3aa1acc095e.png)

![image](https://user-images.githubusercontent.com/88747529/147577787-46ed8713-5043-4df0-8c83-f709b79922e1.png)

5. Round amount in MPT to 4 decimals
![image](https://user-images.githubusercontent.com/88747529/147577906-ce16bdae-7719-4e5c-972f-5fb0dbfdc875.png)

!!Note that user still should be able to insert full amount by typing or pressing MAX. Rounding on balance and MPT is just visual thing.

6. Center SOL address as in design 
Actual:
![image](https://user-images.githubusercontent.com/88747529/147360230-1b7933c3-b939-4131-b8f2-1891d5624460.png)

Design:
![image](https://user-images.githubusercontent.com/88747529/147360286-298f8c02-6960-4f68-927e-e8aef412b2bb.png)

7. Responsiveness (630x714)
![image](https://user-images.githubusercontent.com/88747529/148534744-c24d19eb-bdf3-4af3-bc8d-0355f9a526bf.png)

(950x710)
![image](https://user-images.githubusercontent.com/88747529/148845249-d6b8fa3c-eaf9-48a3-ba7f-6303403f8c37.png)

Mobile:
![image](https://user-images.githubusercontent.com/88747529/148845401-c0ecd0f0-337d-449f-a4e7-70ef0b89eda3.png)

**Comment by QAPanda** [comment]
8. Add loading spinner while waiting to fetch network and balance

https://user-images.githubusercontent.com/88747529/148847221-1a0881c9-efa3-4264-8245-3121fae1677a.mov

**Comment by QAPanda** [comment]
1 :white_check_mark:

**Comment by QAPanda** [comment]
9. Add msg  “Unlock MetaMask to start” here:
![image](https://user-images.githubusercontent.com/88747529/149000928-c9a40f44-c0ea-429c-ad04-b5eca3039d09.png)

or even better force home screen on start:
![image](https://user-images.githubusercontent.com/88747529/148999924-ebe32d22-fa79-4738-aa6c-c0f38b5d2af8.png)

**Comment by QAPanda** [comment]
9 :white_check_mark:
Default on opening:
![image](https://user-images.githubusercontent.com/88747529/149024608-5713c213-252e-47cf-820f-997a24706f45.png)

**Comment by QAPanda** [comment]
10. Sol colors are not updating on skin change

https://user-images.githubusercontent.com/88747529/149094385-d5c9118c-3f00-437d-a3fc-ceefe7dadf2c.mov

**Comment by QAPanda** [comment]
11. If both wallets are disconnected and you connect Solana first (Phantom is locked) you will see both `Connect Wallet` buttons on the top

https://user-images.githubusercontent.com/88747529/149094653-c43194be-b605-4ac6-a711-08ec45cbfb75.mov

**Comment by QAPanda** [comment]
12. Put back download suggestion on landing page
<img width="260" alt="home_png" src="https://user-images.githubusercontent.com/88747529/149115623-20087c00-d59d-423d-b40b-aebd7f6b520d.png">

**Comment by german-schneck** [comment]
1. Done
2. Done
3. Done
4. Done
5. Done
6. Done

**Comment by QAPanda** [comment]
1 :white_check_mark:
2 :white_check_mark:
3 :white_check_mark:
6 :white_check_mark:
9 :white_check_mark:

4 if all zeros display just 2 decimals
![image](https://user-images.githubusercontent.com/88747529/149236581-e13c6a77-3141-4b2b-b516-eb2bea17fc54.png)

5 :negative_squared_cross_mark:
![image](https://user-images.githubusercontent.com/88747529/149236276-29af5e02-f958-4e95-ac84-bd6de55d3a9b.png)

**Comment by german-schneck** [comment]
4 Done
5 Done
9 Done
11 Done

**Comment by german-schneck** [comment]
8. Done
12. Done

**Comment by german-schneck** [comment]
12. Done

**Comment by german-schneck** [comment]
10 Done

**Comment by QAPanda** [comment]
1 :white_check_mark:
2 :white_check_mark:
3 :white_check_mark:
6 :white_check_mark:
8 :white_check_mark:
9 :white_check_mark:
10 :white_check_mark:
11 :white_check_mark:

**Comment by QAPanda** [comment]
To go:
4. Round to 4 decimals. If all are zeros, round to 2 decimals.
5. Round to 4 decimals.
7.
12. Remove `Convert Now` button if wallets are disconnected 
![image](https://user-images.githubusercontent.com/88747529/149316405-30173431-9503-4b81-b88c-7dfc26c88824.png)

**Comment by QAPanda** [comment]
12 :white_check_mark:

**Comment by QAPanda** [comment]
4 :white_check_mark:
5 :white_check_mark:

**Comment by QAPanda** [comment]
7 moved here https://github.com/zignaly-open/zignaly-open-bridge/issues/92
