### ISSUE TITLE
UX improvements 

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#93]
1. Add loading spinner on SOL balance while waiting to reconnect Phantom wallet 

Steps:
- Disconnect Phantom wallet
- Reconnect Phantom wallet
- See Sol balance

https://user-images.githubusercontent.com/88747529/149674167-8134b564-96d7-4eb5-bfb4-c463b7555bd4.mov

2. Type error: Cannot read properties of null (reading 'isTestnet')

Steps:
- In MM switch network to unsupported network (ropsten/kovan)
- Switch back to. supported network (eth/bsc/poly)

https://user-images.githubusercontent.com/88747529/149674184-8b31a8f4-cdc2-4ff6-adbb-c690ca8c230e.mov

3. Responsiveness
![image](https://user-images.githubusercontent.com/88747529/149568199-6ddb9191-d986-4fa8-9411-1b01735a2e21.png)

**Comment by german-schneck** [comment]
2. Done

**Comment by german-schneck** [comment]
1. Done

**Comment by QAPanda** [comment]
1 :white_check_mark:
2 :white_check_mark:

**Comment by german-schneck** [comment]
Will we have a design for point 3?

**Comment by QAPanda** [comment]
I will ask, and move to separate issue https://github.com/zignaly-open/zignaly-open-bridge/issues/95
