### ISSUE TITLE
Error handling - FE msg (clean)

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#94]
When you don’t have for gas, you don’t receive any message regarding the claiming the converted amount.

**Comment by QAPanda** [comment]
Works fine for BSC and POLY.

But if you transfer estimated amount to ETH netw., still will be insufficient and without FE message. Probably amount has changed, and you need more ehts.

<img width="1435" alt="Screen Shot 2022-01-23 at 6 19 01 PM" src="https://user-images.githubusercontent.com/88747529/150690510-ea2cb0fb-ea02-4817-bfb7-05327c16954f.png">

**Comment by german-schneck** [comment]
What solution can we give to this? Increase the deposit limit?

**Comment by german-schneck** [comment]
Try it now.

**Comment by QAPanda** [comment]
We will use default MetaMask functionality for this one. 

Could be improved in future.
