### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#95]
![image](https://user-images.githubusercontent.com/88747529/149568199-6ddb9191-d986-4fa8-9411-1b01735a2e21.png)

**Comment by QAPanda** [comment]
Design example: 
<img width="478" alt="Sol connected-eth disconnected" src="https://user-images.githubusercontent.com/88747529/150410037-558189b2-bc5a-4776-aa10-6816e17ebb2d.png">

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:
