### ISSUE TITLE
Missing consistency between network connected in MM and network selected in bridge UI

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#98]
1. Bug title: Missing consistency between network connected in MM and network selected in bridge UI
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
  Chrome Version 97.0.4692.99 (Official Build) (x86_64)
5. Steps to reproduce:
   - fromChain network is BSC
   - Disconnect bridge from MM wallet (using disconnect button)
   - Switch network to Rinkeby (using bridge UI)
   - Reconnect MM wallet
6. Actual result: Balance in header is from network connected in MM (BSC) but in bridge UI selected network is Rinkeby

Note: Not sure what is possible to do here. 

https://user-images.githubusercontent.com/88747529/150685638-f48debdb-735d-4e7c-979f-608c16f6ca52.mov

**Comment by german-schneck** [comment]
Done

**Comment by QAPanda** [comment]
:white_check_mark:

**Comment by QAPanda** [comment]
Issue with sol:

https://user-images.githubusercontent.com/88747529/150860912-718dcea6-265a-4d10-90e5-897d3aaae844.mov

**Comment by QAPanda** [comment]
:white_check_mark:
