### ISSUE TITLE
Loop on transfer rejection in MM

### ISSUE THREAD

**Issue by QAPanda** [zignaly-open/zignaly-open-bridge#99]
1. Bug title: Loop on transfer rejection in MM
2. URL: https://bridgetest.zignaly.com/
3. Public address/txHash: 
4. OS/Browser version: macOS Big Sur version 11.6.2 /
  Chrome Version 97.0.4692.99 (Official Build) (x86_64)
5. Steps to reproduce:
   - Start transfer
   - Reject to confirm transfer in MM wallet
6. Actual result: Convert button keeps looping after rejection
7. Expected result: Active Convert button 

https://user-images.githubusercontent.com/88747529/150686098-84976b78-1d1c-43eb-9487-cda224a442e5.mov

**Comment by german-schneck** [comment]
Done.

**Comment by QAPanda** [comment]
:white_check_mark:

**Comment by QAPanda** [comment]
Have new one here:

https://user-images.githubusercontent.com/88747529/150849037-45a79329-a8cd-40b8-9003-50e07f909896.mov
